"""Everything a user can do with a finished analysis."""

from clipdesk.actions.article import (
    ARTICLE_FORMATS,
    ARTICLE_SHAPES,
    generate_article,
)
from clipdesk.actions.ask import BEYOND_HEADING, ask
from clipdesk.actions.bookends import (
    ASSET_SUFFIXES,
    apply_bookends,
    assets_dir,
    copy_into_project,
    list_assets,
    list_media,
    media_dir,
    resolve_asset,
    resolve_media,
    store_asset,
    store_media,
)
from clipdesk.actions.cleanup import (
    CleanupOptions,
    explain_cleanup,
    plan_cleanup,
    render_cleanup,
)
from clipdesk.actions.clips import (
    MODES,
    CandidateResult,
    find_candidates,
    rank_spans,
    render_selection,
)
from clipdesk.actions.edits import EditPlan, parse_edit_prompt, render_edit
from clipdesk.actions.editprogram import (
    EditOp,
    EditProgram,
    parse_edit_program,
    render_program,
)
from clipdesk.actions.director import DirectorPlan, PromptContext, plan_prompt
from clipdesk.actions.exports import (
    TRANSCRIPT_FORMATS,
    export_summary,
    export_transcript,
)
from clipdesk.actions.exports_media import (
    ExportPlan,
    export_options,
    plan_export,
    render_export,
)
from clipdesk.actions.notes import generate_notes
from clipdesk.actions.intro import (
    BUILT_IN_STYLES,
    CATALOG_STYLES,
    IntroPlan,
    IntroScene,
    IntroStyle,
    available_styles,
    fit_narration,
    import_custom_style,
    install_catalog_style,
    plan_intro,
    render_intro,
    resolve_style,
    shot_labels,
)
from clipdesk.actions.outputs import (
    OutputError,
    bundle_outputs,
    delete_output,
    delete_source,
    resolve_outputs,
    reveal,
    rename_output,
    source_info,
)

__all__ = [
    "MODES",
    "ARTICLE_FORMATS",
    "ARTICLE_SHAPES",
    "BEYOND_HEADING",
    "TRANSCRIPT_FORMATS",
    "CandidateResult",
    "CleanupOptions",
    "EditPlan",
    "EditOp",
    "EditProgram",
    "parse_edit_program",
    "render_program",
    "DirectorPlan",
    "PromptContext",
    "plan_prompt",
    "ExportPlan",
    "IntroPlan",
    "IntroScene",
    "IntroStyle",
    "BUILT_IN_STYLES",
    "CATALOG_STYLES",
    "OutputError",
    "apply_bookends",
    "available_styles",
    "fit_narration",
    "ASSET_SUFFIXES",
    "assets_dir",
    "bundle_outputs",
    "copy_into_project",
    "delete_output",
    "delete_source",
    "explain_cleanup",
    "export_summary",
    "export_transcript",
    "export_options",
    "plan_export",
    "render_export",
    "find_candidates",
    "generate_article",    "generate_notes",
    "import_custom_style",
    "install_catalog_style",
    "list_assets",
    "list_media",
    "media_dir",
    "plan_cleanup",
    "plan_intro",
    "parse_edit_prompt",
    "rank_spans",
    "render_cleanup",
    "render_edit",
    "render_intro",
    "resolve_style",
    "render_selection",
    "resolve_asset",
    "resolve_media",
    "store_asset",
    "store_media",
    "resolve_outputs",
    "reveal",
    "rename_output",
    "shot_labels",
    "source_info",
]
